package co.nuqui.tech.msdeposits.domain.dto;

public class TransactionConstants {
    public static final String TRANSACTION_STATUS_INSUFICIENT_FUNDS = "TRANSACTION_STATUS_INSUFICIENT_FUNDS";
    public static final String TRANSACTION_STATUS_COMPLETED = "TRANSACTION_STATUS_COMPLETED";
    public static final String TRANSACTION_STATUS_PROCESSING = "TRANSACTION_STATUS_PROCESSING";
    public static final String TRANSACTION_STATUS_QUEUED = "TRANSACTION_STATUS_QUEUED";
    public static final String TRANSACTION_STATUS_DEPOSIT_FROM_NOT_FOUND = "TRANSACTION_STATUS_DEPOSIT_FROM_NOT_FOUND";
    public static final String TRANSACTION_STATUS_DEPOSIT_TO_NOT_FOUND = "TRANSACTION_STATUS_DEPOSIT_FROM_NOT_FOUND";
}